// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatService.proto

package com.ncirl.thermostat;

public interface StreamThermoStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.thermostat.StreamThermoStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 streamTemp = 3;</code>
   */
  int getStreamTemp();
}
