// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatService.proto

package com.ncirl.thermostat;

public interface StreamThermoStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.thermostat.StreamThermoStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
