// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatService.proto

package com.ncirl.thermostat;

public interface UnaryThermostatStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.thermostat.UnaryThermostatStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
   * </pre>
   *
   * <code>int32 temp = 1;</code>
   */
  int getTemp();
}
