// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.ncirl.storage;

public interface StorageStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.storage.StorageStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 storageId = 1;</code>
   */
  int getStorageId();

  /**
   * <code>string storageStatus = 2;</code>
   */
  java.lang.String getStorageStatus();
  /**
   * <code>string storageStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getStorageStatusBytes();
}
