// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.ncirl.storage;

public interface UnaryStorageStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.storage.UnaryStorageStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
   * </pre>
   *
   * <code>string storageId = 1;</code>
   */
  java.lang.String getStorageId();
  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
   * </pre>
   *
   * <code>string storageId = 1;</code>
   */
  com.google.protobuf.ByteString
      getStorageIdBytes();

  /**
   * <code>string storageStatus = 2;</code>
   */
  java.lang.String getStorageStatus();
  /**
   * <code>string storageStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getStorageStatusBytes();
}
