// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.ncirl.storage;

/**
 * Protobuf type {@code com.ncirl.storage.UnaryStorageStatusResponse}
 */
public  final class UnaryStorageStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.storage.UnaryStorageStatusResponse)
    UnaryStorageStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnaryStorageStatusResponse.newBuilder() to construct.
  private UnaryStorageStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnaryStorageStatusResponse() {
    storageId_ = "";
    storageStatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnaryStorageStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            storageId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            storageStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.storage.UnaryStorageStatusResponse.class, com.ncirl.storage.UnaryStorageStatusResponse.Builder.class);
  }

  public static final int STORAGEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object storageId_;
  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
   * </pre>
   *
   * <code>string storageId = 1;</code>
   */
  public java.lang.String getStorageId() {
    java.lang.Object ref = storageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      storageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
   * </pre>
   *
   * <code>string storageId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStorageIdBytes() {
    java.lang.Object ref = storageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      storageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORAGESTATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object storageStatus_;
  /**
   * <code>string storageStatus = 2;</code>
   */
  public java.lang.String getStorageStatus() {
    java.lang.Object ref = storageStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      storageStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string storageStatus = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStorageStatusBytes() {
    java.lang.Object ref = storageStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      storageStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStorageIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, storageId_);
    }
    if (!getStorageStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, storageStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStorageIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, storageId_);
    }
    if (!getStorageStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, storageStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.storage.UnaryStorageStatusResponse)) {
      return super.equals(obj);
    }
    com.ncirl.storage.UnaryStorageStatusResponse other = (com.ncirl.storage.UnaryStorageStatusResponse) obj;

    boolean result = true;
    result = result && getStorageId()
        .equals(other.getStorageId());
    result = result && getStorageStatus()
        .equals(other.getStorageStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORAGEID_FIELD_NUMBER;
    hash = (53 * hash) + getStorageId().hashCode();
    hash = (37 * hash) + STORAGESTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStorageStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.storage.UnaryStorageStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ncirl.storage.UnaryStorageStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.storage.UnaryStorageStatusResponse)
      com.ncirl.storage.UnaryStorageStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.storage.UnaryStorageStatusResponse.class, com.ncirl.storage.UnaryStorageStatusResponse.Builder.class);
    }

    // Construct using com.ncirl.storage.UnaryStorageStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      storageId_ = "";

      storageStatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstanceForType() {
      return com.ncirl.storage.UnaryStorageStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse build() {
      com.ncirl.storage.UnaryStorageStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse buildPartial() {
      com.ncirl.storage.UnaryStorageStatusResponse result = new com.ncirl.storage.UnaryStorageStatusResponse(this);
      result.storageId_ = storageId_;
      result.storageStatus_ = storageStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.storage.UnaryStorageStatusResponse) {
        return mergeFrom((com.ncirl.storage.UnaryStorageStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.storage.UnaryStorageStatusResponse other) {
      if (other == com.ncirl.storage.UnaryStorageStatusResponse.getDefaultInstance()) return this;
      if (!other.getStorageId().isEmpty()) {
        storageId_ = other.storageId_;
        onChanged();
      }
      if (!other.getStorageStatus().isEmpty()) {
        storageStatus_ = other.storageStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.storage.UnaryStorageStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.storage.UnaryStorageStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object storageId_ = "";
    /**
     * <pre>
     * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
     * </pre>
     *
     * <code>string storageId = 1;</code>
     */
    public java.lang.String getStorageId() {
      java.lang.Object ref = storageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
     * </pre>
     *
     * <code>string storageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStorageIdBytes() {
      java.lang.Object ref = storageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
     * </pre>
     *
     * <code>string storageId = 1;</code>
     */
    public Builder setStorageId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      storageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
     * </pre>
     *
     * <code>string storageId = 1;</code>
     */
    public Builder clearStorageId() {
      
      storageId_ = getDefaultInstance().getStorageId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dados que serao passados para o cliente, apos o request. Sao as informacoes do storage.
     * </pre>
     *
     * <code>string storageId = 1;</code>
     */
    public Builder setStorageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      storageId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object storageStatus_ = "";
    /**
     * <code>string storageStatus = 2;</code>
     */
    public java.lang.String getStorageStatus() {
      java.lang.Object ref = storageStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storageStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string storageStatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStorageStatusBytes() {
      java.lang.Object ref = storageStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string storageStatus = 2;</code>
     */
    public Builder setStorageStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      storageStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string storageStatus = 2;</code>
     */
    public Builder clearStorageStatus() {
      
      storageStatus_ = getDefaultInstance().getStorageStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string storageStatus = 2;</code>
     */
    public Builder setStorageStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      storageStatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.storage.UnaryStorageStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.storage.UnaryStorageStatusResponse)
  private static final com.ncirl.storage.UnaryStorageStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.storage.UnaryStorageStatusResponse();
  }

  public static com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnaryStorageStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<UnaryStorageStatusResponse>() {
    @java.lang.Override
    public UnaryStorageStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnaryStorageStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnaryStorageStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnaryStorageStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

