// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.ncirl.storage;

/**
 * Protobuf type {@code com.ncirl.storage.UnaryStorageStatusResponse}
 */
public  final class UnaryStorageStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.storage.UnaryStorageStatusResponse)
    UnaryStorageStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnaryStorageStatusResponse.newBuilder() to construct.
  private UnaryStorageStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnaryStorageStatusResponse() {
    storageStatusList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnaryStorageStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              storageStatusList_ = new java.util.ArrayList<com.ncirl.storage.StorageStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            storageStatusList_.add(
                input.readMessage(com.ncirl.storage.StorageStatus.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        storageStatusList_ = java.util.Collections.unmodifiableList(storageStatusList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.storage.UnaryStorageStatusResponse.class, com.ncirl.storage.UnaryStorageStatusResponse.Builder.class);
  }

  public static final int STORAGESTATUSLIST_FIELD_NUMBER = 1;
  private java.util.List<com.ncirl.storage.StorageStatus> storageStatusList_;
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  public java.util.List<com.ncirl.storage.StorageStatus> getStorageStatusListList() {
    return storageStatusList_;
  }
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  public java.util.List<? extends com.ncirl.storage.StorageStatusOrBuilder> 
      getStorageStatusListOrBuilderList() {
    return storageStatusList_;
  }
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  public int getStorageStatusListCount() {
    return storageStatusList_.size();
  }
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  public com.ncirl.storage.StorageStatus getStorageStatusList(int index) {
    return storageStatusList_.get(index);
  }
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  public com.ncirl.storage.StorageStatusOrBuilder getStorageStatusListOrBuilder(
      int index) {
    return storageStatusList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < storageStatusList_.size(); i++) {
      output.writeMessage(1, storageStatusList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < storageStatusList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, storageStatusList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.storage.UnaryStorageStatusResponse)) {
      return super.equals(obj);
    }
    com.ncirl.storage.UnaryStorageStatusResponse other = (com.ncirl.storage.UnaryStorageStatusResponse) obj;

    boolean result = true;
    result = result && getStorageStatusListList()
        .equals(other.getStorageStatusListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStorageStatusListCount() > 0) {
      hash = (37 * hash) + STORAGESTATUSLIST_FIELD_NUMBER;
      hash = (53 * hash) + getStorageStatusListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.storage.UnaryStorageStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.storage.UnaryStorageStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ncirl.storage.UnaryStorageStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.storage.UnaryStorageStatusResponse)
      com.ncirl.storage.UnaryStorageStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.storage.UnaryStorageStatusResponse.class, com.ncirl.storage.UnaryStorageStatusResponse.Builder.class);
    }

    // Construct using com.ncirl.storage.UnaryStorageStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStorageStatusListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (storageStatusListBuilder_ == null) {
        storageStatusList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        storageStatusListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.storage.StorageServiceProto.internal_static_com_ncirl_storage_UnaryStorageStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstanceForType() {
      return com.ncirl.storage.UnaryStorageStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse build() {
      com.ncirl.storage.UnaryStorageStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.storage.UnaryStorageStatusResponse buildPartial() {
      com.ncirl.storage.UnaryStorageStatusResponse result = new com.ncirl.storage.UnaryStorageStatusResponse(this);
      int from_bitField0_ = bitField0_;
      if (storageStatusListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          storageStatusList_ = java.util.Collections.unmodifiableList(storageStatusList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.storageStatusList_ = storageStatusList_;
      } else {
        result.storageStatusList_ = storageStatusListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.storage.UnaryStorageStatusResponse) {
        return mergeFrom((com.ncirl.storage.UnaryStorageStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.storage.UnaryStorageStatusResponse other) {
      if (other == com.ncirl.storage.UnaryStorageStatusResponse.getDefaultInstance()) return this;
      if (storageStatusListBuilder_ == null) {
        if (!other.storageStatusList_.isEmpty()) {
          if (storageStatusList_.isEmpty()) {
            storageStatusList_ = other.storageStatusList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStorageStatusListIsMutable();
            storageStatusList_.addAll(other.storageStatusList_);
          }
          onChanged();
        }
      } else {
        if (!other.storageStatusList_.isEmpty()) {
          if (storageStatusListBuilder_.isEmpty()) {
            storageStatusListBuilder_.dispose();
            storageStatusListBuilder_ = null;
            storageStatusList_ = other.storageStatusList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            storageStatusListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStorageStatusListFieldBuilder() : null;
          } else {
            storageStatusListBuilder_.addAllMessages(other.storageStatusList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.storage.UnaryStorageStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.storage.UnaryStorageStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ncirl.storage.StorageStatus> storageStatusList_ =
      java.util.Collections.emptyList();
    private void ensureStorageStatusListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        storageStatusList_ = new java.util.ArrayList<com.ncirl.storage.StorageStatus>(storageStatusList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ncirl.storage.StorageStatus, com.ncirl.storage.StorageStatus.Builder, com.ncirl.storage.StorageStatusOrBuilder> storageStatusListBuilder_;

    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public java.util.List<com.ncirl.storage.StorageStatus> getStorageStatusListList() {
      if (storageStatusListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(storageStatusList_);
      } else {
        return storageStatusListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public int getStorageStatusListCount() {
      if (storageStatusListBuilder_ == null) {
        return storageStatusList_.size();
      } else {
        return storageStatusListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public com.ncirl.storage.StorageStatus getStorageStatusList(int index) {
      if (storageStatusListBuilder_ == null) {
        return storageStatusList_.get(index);
      } else {
        return storageStatusListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder setStorageStatusList(
        int index, com.ncirl.storage.StorageStatus value) {
      if (storageStatusListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStorageStatusListIsMutable();
        storageStatusList_.set(index, value);
        onChanged();
      } else {
        storageStatusListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder setStorageStatusList(
        int index, com.ncirl.storage.StorageStatus.Builder builderForValue) {
      if (storageStatusListBuilder_ == null) {
        ensureStorageStatusListIsMutable();
        storageStatusList_.set(index, builderForValue.build());
        onChanged();
      } else {
        storageStatusListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder addStorageStatusList(com.ncirl.storage.StorageStatus value) {
      if (storageStatusListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStorageStatusListIsMutable();
        storageStatusList_.add(value);
        onChanged();
      } else {
        storageStatusListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder addStorageStatusList(
        int index, com.ncirl.storage.StorageStatus value) {
      if (storageStatusListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStorageStatusListIsMutable();
        storageStatusList_.add(index, value);
        onChanged();
      } else {
        storageStatusListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder addStorageStatusList(
        com.ncirl.storage.StorageStatus.Builder builderForValue) {
      if (storageStatusListBuilder_ == null) {
        ensureStorageStatusListIsMutable();
        storageStatusList_.add(builderForValue.build());
        onChanged();
      } else {
        storageStatusListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder addStorageStatusList(
        int index, com.ncirl.storage.StorageStatus.Builder builderForValue) {
      if (storageStatusListBuilder_ == null) {
        ensureStorageStatusListIsMutable();
        storageStatusList_.add(index, builderForValue.build());
        onChanged();
      } else {
        storageStatusListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder addAllStorageStatusList(
        java.lang.Iterable<? extends com.ncirl.storage.StorageStatus> values) {
      if (storageStatusListBuilder_ == null) {
        ensureStorageStatusListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, storageStatusList_);
        onChanged();
      } else {
        storageStatusListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder clearStorageStatusList() {
      if (storageStatusListBuilder_ == null) {
        storageStatusList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        storageStatusListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public Builder removeStorageStatusList(int index) {
      if (storageStatusListBuilder_ == null) {
        ensureStorageStatusListIsMutable();
        storageStatusList_.remove(index);
        onChanged();
      } else {
        storageStatusListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public com.ncirl.storage.StorageStatus.Builder getStorageStatusListBuilder(
        int index) {
      return getStorageStatusListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public com.ncirl.storage.StorageStatusOrBuilder getStorageStatusListOrBuilder(
        int index) {
      if (storageStatusListBuilder_ == null) {
        return storageStatusList_.get(index);  } else {
        return storageStatusListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public java.util.List<? extends com.ncirl.storage.StorageStatusOrBuilder> 
         getStorageStatusListOrBuilderList() {
      if (storageStatusListBuilder_ != null) {
        return storageStatusListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(storageStatusList_);
      }
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public com.ncirl.storage.StorageStatus.Builder addStorageStatusListBuilder() {
      return getStorageStatusListFieldBuilder().addBuilder(
          com.ncirl.storage.StorageStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public com.ncirl.storage.StorageStatus.Builder addStorageStatusListBuilder(
        int index) {
      return getStorageStatusListFieldBuilder().addBuilder(
          index, com.ncirl.storage.StorageStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
     */
    public java.util.List<com.ncirl.storage.StorageStatus.Builder> 
         getStorageStatusListBuilderList() {
      return getStorageStatusListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ncirl.storage.StorageStatus, com.ncirl.storage.StorageStatus.Builder, com.ncirl.storage.StorageStatusOrBuilder> 
        getStorageStatusListFieldBuilder() {
      if (storageStatusListBuilder_ == null) {
        storageStatusListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ncirl.storage.StorageStatus, com.ncirl.storage.StorageStatus.Builder, com.ncirl.storage.StorageStatusOrBuilder>(
                storageStatusList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        storageStatusList_ = null;
      }
      return storageStatusListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.storage.UnaryStorageStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.storage.UnaryStorageStatusResponse)
  private static final com.ncirl.storage.UnaryStorageStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.storage.UnaryStorageStatusResponse();
  }

  public static com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnaryStorageStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<UnaryStorageStatusResponse>() {
    @java.lang.Override
    public UnaryStorageStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnaryStorageStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnaryStorageStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnaryStorageStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.storage.UnaryStorageStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

