// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package com.ncirl.storage;

public interface UnaryStorageStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.storage.UnaryStorageStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  java.util.List<com.ncirl.storage.StorageStatus> 
      getStorageStatusListList();
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  com.ncirl.storage.StorageStatus getStorageStatusList(int index);
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  int getStorageStatusListCount();
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  java.util.List<? extends com.ncirl.storage.StorageStatusOrBuilder> 
      getStorageStatusListOrBuilderList();
  /**
   * <code>repeated .com.ncirl.storage.StorageStatus storageStatusList = 1;</code>
   */
  com.ncirl.storage.StorageStatusOrBuilder getStorageStatusListOrBuilder(
      int index);
}
