// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

public final class RobotServiceProto {
  private RobotServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_UnaryRobotStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_UnaryRobotStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_StreamRobotStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_StreamRobotStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_StreamRobotStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_StreamRobotStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_BidirectionalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_BidirectionalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_BidirectionalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_BidirectionalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_robot_RobotStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_robot_RobotStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RobotService.proto\022\017com.ncirl.robot\032\033g" +
      "oogle/protobuf/empty.proto\"]\n\030UnaryRobot" +
      "StatusResponse\022\021\n\trobotName\030\001 \001(\t\022\023\n\013rob" +
      "otStatus\030\002 \001(\t\022\031\n\021robotBatteryLevel\030\003 \001(" +
      "\005\"[\n\030StreamRobotStatusRequest\022\021\n\trobotNa" +
      "me\030\001 \001(\t\022\020\n\010dateTime\030\002 \001(\t\022\032\n\022streamBatt" +
      "eryLevel\030\003 \001(\t\",\n\031StreamRobotStatusRespo" +
      "nse\022\017\n\007message\030\001 \001(\t\"\'\n\024BidirectionalReq" +
      "uest\022\017\n\007message\030\001 \001(\t\"(\n\025BidirectionalRe" +
      "sponse\022\017\n\007message\030\001 \001(\t\"\"\n\013RobotStatus\022\023" +
      "\n\013robotStatus\030\001 \001(\t2\212\003\n\014RobotService\022Z\n\025" +
      "getCurrentRobotStatus\022\026.google.protobuf." +
      "Empty\032).com.ncirl.robot.UnaryRobotStatus" +
      "Response\022l\n\021streamRobotStatus\022).com.ncir" +
      "l.robot.StreamRobotStatusRequest\032*.com.n" +
      "cirl.robot.StreamRobotStatusResponse(\001\022h" +
      "\n\023bidirectionalStream\022%.com.ncirl.robot." +
      "BidirectionalRequest\032&.com.ncirl.robot.B" +
      "idirectionalResponse(\0010\001\022F\n\016SetRobotStat" +
      "us\022\034.com.ncirl.robot.RobotStatus\032\026.googl" +
      "e.protobuf.EmptyB&\n\017com.ncirl.robotB\021Rob" +
      "otServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_ncirl_robot_UnaryRobotStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_robot_UnaryRobotStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_UnaryRobotStatusResponse_descriptor,
        new java.lang.String[] { "RobotName", "RobotStatus", "RobotBatteryLevel", });
    internal_static_com_ncirl_robot_StreamRobotStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_robot_StreamRobotStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_StreamRobotStatusRequest_descriptor,
        new java.lang.String[] { "RobotName", "DateTime", "StreamBatteryLevel", });
    internal_static_com_ncirl_robot_StreamRobotStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ncirl_robot_StreamRobotStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_StreamRobotStatusResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_robot_BidirectionalRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ncirl_robot_BidirectionalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_BidirectionalRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_robot_BidirectionalResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ncirl_robot_BidirectionalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_BidirectionalResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ncirl_robot_RobotStatus_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ncirl_robot_RobotStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_robot_RobotStatus_descriptor,
        new java.lang.String[] { "RobotStatus", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
