// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

public interface RobotStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robot.RobotStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string robotStatus = 1;</code>
   */
  java.lang.String getRobotStatus();
  /**
   * <code>string robotStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getRobotStatusBytes();
}
