// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

public interface StreamRobotStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robot.StreamRobotStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string robotName = 1;</code>
   */
  java.lang.String getRobotName();
  /**
   * <code>string robotName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRobotNameBytes();

  /**
   * <code>string dateTime = 2;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
