// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

/**
 * Protobuf type {@code com.ncirl.robot.UnaryRobotStatusRequest}
 */
public  final class UnaryRobotStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.robot.UnaryRobotStatusRequest)
    UnaryRobotStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnaryRobotStatusRequest.newBuilder() to construct.
  private UnaryRobotStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnaryRobotStatusRequest() {
    robotRequestMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnaryRobotStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            robotRequestMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.robot.RobotServiceProto.internal_static_com_ncirl_robot_UnaryRobotStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.robot.RobotServiceProto.internal_static_com_ncirl_robot_UnaryRobotStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.robot.UnaryRobotStatusRequest.class, com.ncirl.robot.UnaryRobotStatusRequest.Builder.class);
  }

  public static final int ROBOTREQUESTMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object robotRequestMessage_;
  /**
   * <pre>
   * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
   * </pre>
   *
   * <code>string robotRequestMessage = 1;</code>
   */
  public java.lang.String getRobotRequestMessage() {
    java.lang.Object ref = robotRequestMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      robotRequestMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
   * </pre>
   *
   * <code>string robotRequestMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRobotRequestMessageBytes() {
    java.lang.Object ref = robotRequestMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      robotRequestMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRobotRequestMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, robotRequestMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRobotRequestMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, robotRequestMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.robot.UnaryRobotStatusRequest)) {
      return super.equals(obj);
    }
    com.ncirl.robot.UnaryRobotStatusRequest other = (com.ncirl.robot.UnaryRobotStatusRequest) obj;

    boolean result = true;
    result = result && getRobotRequestMessage()
        .equals(other.getRobotRequestMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROBOTREQUESTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getRobotRequestMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.robot.UnaryRobotStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.robot.UnaryRobotStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ncirl.robot.UnaryRobotStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.robot.UnaryRobotStatusRequest)
      com.ncirl.robot.UnaryRobotStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.robot.RobotServiceProto.internal_static_com_ncirl_robot_UnaryRobotStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.robot.RobotServiceProto.internal_static_com_ncirl_robot_UnaryRobotStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.robot.UnaryRobotStatusRequest.class, com.ncirl.robot.UnaryRobotStatusRequest.Builder.class);
    }

    // Construct using com.ncirl.robot.UnaryRobotStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      robotRequestMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.robot.RobotServiceProto.internal_static_com_ncirl_robot_UnaryRobotStatusRequest_descriptor;
    }

    @java.lang.Override
    public com.ncirl.robot.UnaryRobotStatusRequest getDefaultInstanceForType() {
      return com.ncirl.robot.UnaryRobotStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.robot.UnaryRobotStatusRequest build() {
      com.ncirl.robot.UnaryRobotStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.robot.UnaryRobotStatusRequest buildPartial() {
      com.ncirl.robot.UnaryRobotStatusRequest result = new com.ncirl.robot.UnaryRobotStatusRequest(this);
      result.robotRequestMessage_ = robotRequestMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.robot.UnaryRobotStatusRequest) {
        return mergeFrom((com.ncirl.robot.UnaryRobotStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.robot.UnaryRobotStatusRequest other) {
      if (other == com.ncirl.robot.UnaryRobotStatusRequest.getDefaultInstance()) return this;
      if (!other.getRobotRequestMessage().isEmpty()) {
        robotRequestMessage_ = other.robotRequestMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.robot.UnaryRobotStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.robot.UnaryRobotStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object robotRequestMessage_ = "";
    /**
     * <pre>
     * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
     * </pre>
     *
     * <code>string robotRequestMessage = 1;</code>
     */
    public java.lang.String getRobotRequestMessage() {
      java.lang.Object ref = robotRequestMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        robotRequestMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
     * </pre>
     *
     * <code>string robotRequestMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRobotRequestMessageBytes() {
      java.lang.Object ref = robotRequestMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        robotRequestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
     * </pre>
     *
     * <code>string robotRequestMessage = 1;</code>
     */
    public Builder setRobotRequestMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      robotRequestMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
     * </pre>
     *
     * <code>string robotRequestMessage = 1;</code>
     */
    public Builder clearRobotRequestMessage() {
      
      robotRequestMessage_ = getDefaultInstance().getRobotRequestMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
     * </pre>
     *
     * <code>string robotRequestMessage = 1;</code>
     */
    public Builder setRobotRequestMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      robotRequestMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.robot.UnaryRobotStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.robot.UnaryRobotStatusRequest)
  private static final com.ncirl.robot.UnaryRobotStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.robot.UnaryRobotStatusRequest();
  }

  public static com.ncirl.robot.UnaryRobotStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnaryRobotStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<UnaryRobotStatusRequest>() {
    @java.lang.Override
    public UnaryRobotStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnaryRobotStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnaryRobotStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnaryRobotStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.robot.UnaryRobotStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

