// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

public interface UnaryRobotStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robot.UnaryRobotStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do robot.
   * </pre>
   *
   * <code>string robotName = 1;</code>
   */
  java.lang.String getRobotName();
  /**
   * <pre>
   * Dados que serao passados para o cliente, apos o request. Sao as informacoes do robot.
   * </pre>
   *
   * <code>string robotName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRobotNameBytes();

  /**
   * <code>string robotStatus = 2;</code>
   */
  java.lang.String getRobotStatus();
  /**
   * <code>string robotStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getRobotStatusBytes();

  /**
   * <code>int32 robotBatteryLevel = 3;</code>
   */
  int getRobotBatteryLevel();
}
