// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotService.proto

package com.ncirl.robot;

public interface UnaryRobotStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.robot.UnaryRobotStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
   * </pre>
   *
   * <code>string robotRequestMessage = 1;</code>
   */
  java.lang.String getRobotRequestMessage();
  /**
   * <pre>
   * Mensagem adicional extra para enviar ao servidor. Exemplo: "Me mande os dados do robo"
   * </pre>
   *
   * <code>string robotRequestMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRobotRequestMessageBytes();
}
